// https://seeklogo.com/search?q=dagster
export const devProject = [
	{
		featured: true,
		type: "Projet Sélectionné",
		title: "Portfolio",
		summary: "My personal portfolio website.",
		date: "2024-02-02",
		img: "/images/projects/portfolio.png",
		link: "",
		github: "https://github.com/slamer59/portfolio",
		technologies: ["nextjs", "typescript", "tailwind"],
		license: "Other",
	},
	{
		featured: false,
		type: "Workflow",
		title: "mage-ai",
		summary:
			"The modern replacement for Airflow. Build, run, and manage data pipelines for integrating and transforming data.",
		date: "2023-11-16",
		img: "/images/projects/mageai.png",
		link: "",
		github: "https://github.com/mage-ai/mage-ai",
		technologies: ["python"],
		license: "Apache License 2.0",
	},
	{
		featured: false,
		type: "LLM",
		title: "langcorn",
		summary: "Serving LangChain LLM apps automatically with FastApi.",
		date: "2023-08-24",
		img: "/images/projects/langcorn.png",
		link: "",
		github: "https://github.com/msoedov/langcorn",
		technologies: ["python"],
		license: "MIT License",
	},

	{
		featured: true,
		type: "Data",
		title: "hvplot_panel",
		summary: "Combine hvplot graphs with panel functionalities.",
		date: "2022-12-27",
		img: "/images/projects/hvplot_panel.png",
		link: "",
		github: "https://github.com/slamer59/hvplot_panel",
		technologies: ["jupyter"],
		license: "MIT License",
	},
	{
		featured: true,
		type: "Jokosun",
		title: "saleor",
		summary:
			"Used in Jokosun e-commerce, A modular, high performance, headless e-commerce platform built with python, GraphQL, Django, and React.",
		date: "2022-02-09",
		img: "/images/projects/saleor.png",
		link: "https://www.jokosun.com",
		github: "https://github.com/saleor/saleor",
		technologies: ["python", "django", "graphql", "nextjs"],
		license: "Jokosun",
	},
	{
		featured: false,
		type: "CRM",
		title: "Strapi CRM",
		summary: "Strapi Documentation mono-repo.",
		date: "2022-04-27",
		img: "/images/projects/strapi.png",
		link: "",
		github: "https://github.com/strapi/documentation",
		technologies: ["javascript", "docker", "graphql"],
		license: "Other",
	},
	// {
	//     "featured": false,
	//     "type": "private",
	//     "title": "cash-flow-dashboard",
	//     "summary": "",
	//     "date": "2022-04-03",
	//     "img": "",
	//     "link": "",
	//     "github": "",
	//     "technologies": ["html"],
	//     "license": ""
	// },
	{
		featured: true,
		type: "private",
		title: "helm-chart-viz",
		summary:
			"Developped in Jokosun. Help to represent the helm chart depenceies in a visual way.",
		date: "2022-03-23",
		img: "",
		link: "",
		github: "https://github.com/slamer59/helm-chart-viz",
		technologies: ["python", "helm"],
		license: "MIT",
	},

	{
		featured: false,
		type: "private",
		title: "openxml-document",
		summary: "Parser for docx with schema and xsdata",
		date: "2022-02-19",
		img: "/images/projects/openxml.png",
		link: "",
		github: "https://github.com/slamer59/openxml-document",
		technologies: ["python"],
		license: "",
	},
	{
		featured: false,
		type: "public",
		title: "strapi-docker",
		summary: "Install and run your first Strapi project using Docker.",
		date: "2022-02-12",
		img: "",
		link: "",
		github: "https://github.com/strapi/strapi-docker",
		technologies: ["javascript", "docker"],
		license: "MIT License",
	},
	{
		featured: true,
		type: "public",
		title: "dagster",
		summary:
			"Powerfull data orchestrator for machine learning, analytics, and ETL.",
		date: "2022-01-27",
		img: "/images/projects/dagster.webp",
		link: "",
		github: "https://github.com/dagster-io/dagster",
		technologies: [
			"python",
			"dagster",
			"typescript",
			"docker",
			"helm",
			"kubernetes",
		],
		license: "Apache License 2.0",
	},
	{
		featured: false,
		type: "Workflow",
		title: "dagster-meltano",
		summary: "A Dagster plugin that allows you to run Meltano in Dagster.",
		date: "2023-01-15",
		img: "/images/projects/dagster.webp",
		link: "",
		github: "https://github.com/quantile-development/dagster-meltano",
		technologies: ["python", "dagster", "nextjs"],
		license: "MIT License",
	},
	// {
	//     "featured": false,
	//     "type": "template",
	//     "title": "api-platform",
	//     "summary": "Create REST and GraphQL APIs, scaffold Jamstack webapps, stream changes in real-time.",
	//     "date": "2021-12-24",
	//     "img": "",
	//     "link": "",
	//     "github": "https://github.com/api-platform/api-platform",
	//     "technologies": ["typescript"],
	//     "license": "MIT License"
	// },
	// {
	//     "featured": false,
	//     "type": "public",
	//     "title": "xmldiff",
	//     "summary": "A library and command line utility for diffing xml",
	//     "date": "2021-11-26",
	//     "img": "",
	//     "link": "",
	//     "github": "https://github.com/Shoobx/xmldiff",
	//     "technologies": ["python"],
	//     "license": "MIT License"
	// },
	{
		featured: false,
		type: "public",
		title: "pdf2docxnogui",
		summary: "Parse PDF file with PyMuPDF and generate docx with python-docx",
		date: "2021-10-29",
		img: "",
		link: "",
		github: "https://github.com/mateusmb/pdf2docxnogui",
		technologies: ["python"],
		license: "GNU General Public License v3.0",
	},
	// {
	//     "featured": false,
	//     "type": "public",
	//     "title": "sphinx-material",
	//     "summary": "A material-based, responsive theme inspired by mkdocs-material",
	//     "date": "2021-10-06",
	//     "img": "",
	//     "link": "",
	//     "github": "https://github.com/bashtage/sphinx-material",
	//     "technologies": ["css"],
	//     "license": "Other"
	// },
	{
		featured: false,
		type: "public",
		title: "fastapi-crudrouter",
		summary:
			"A dynamic FastAPI router that automatically creates CRUD routes for your models",
		date: "2021-09-06",
		img: "",
		link: "",
		github: "https://github.com/awtkns/fastapi-crudrouter",
		technologies: ["python"],
		license: "MIT License",
	},
	{
		featured: false,
		type: "public",
		title: "scikit-decide",
		summary:
			"AI framework for Reinforcement Learning, Automated Planning and Scheduling",
		date: "2021-06-23",
		img: "",
		link: "",
		github: "https://github.com/airbus/scikit-decide",
		technologies: ["c++"],
		license: "MIT License",
	},

	{
		featured: true,
		type: "Workflow",
		title: "argocd",
		summary: "A declarative orchestrator for Kubernetes used in Jokosun stack",
		date: "2021-05-10",
		img: "/images/projects/argocd.png",
		link: "",
		github: "",
		technologies: ["python", "helm", "kubernetes"],
		license: "",
	},
	{
		featured: false,
		type: "public",
		title: "dagster-argocd-configuration",
		summary: "",
		date: "2022-02-23",
		img: "/images/projects/dagster.webp",
		link: "",
		github: "https://github.com/slamer59/dagster-argocd-configuration",
		technologies: ["mustache"],
		license: "",
	},

	{
		featured: true,
		type: "public",
		title: "dagster-another-user-code",
		summary: "Test dagster-central",
		date: "2021-05-10",
		img: "/images/projects/dagster.webp",
		link: "",
		github: "https://github.com/slamer59/dagster-another-user-code",
		technologies: ["python", "dagster", "docker", "helm", "kubernetes"],
		license: "",
	},
	{
		featured: true,
		type: "template",
		title: "dagster-user-code",
		summary: "",
		date: "2021-05-09",
		img: "/images/projects/dagster.webp",
		link: "",
		github: "https://github.com/slamer59/dagster-user-code",
		technologies: ["python", "dagster", "docker", "helm", "kubernetes"],
		license: "",
	},
	{
		featured: false,
		type: "public",
		title: "dagster-multifilesprocessing",
		summary: "Multifilesprocessing of documents with dagster",
		date: "2021-05-22",
		img: "/images/projects/dagster.webp",
		link: "",
		github: "",
		technologies: ["python", "dagster"],
		license: "MIT License",
	},
	// {
	//     "featured": false,
	//     "type": "public",
	//     "title": "flowchartstorm",
	//     "summary": "Use of react-diagrams from stormproject",
	//     "date": "2021-05-12",
	//     "img": "",
	//     "link": "",
	//     "github": "",
	//     "technologies": ["javascript"],
	//     "license": ""
	// },
	{
		featured: false,
		type: "public",
		title: "dagster-central",
		summary: "",
		date: "2021-05-11",
		img: "/images/projects/dagster.webp",
		link: "",
		github: "https://github.com/slamer59/dagster-central",
		technologies: ["python", "dagster", "docker", "helm", "kubernetes"],
		license: "",
	},
	{
		featured: false,
		type: "public",
		title: "energies-domestique",
		summary: "",
		date: "2021-04-20",
		img: "",
		link: "",
		github: "",
		technologies: ["jupyter"],
		license: "Apache License 2.0",
	},
	{
		featured: false,
		type: "public",
		title: "energies_domestiques",
		summary: "Setup Consumer for MQTT",
		date: "2021-03-25",
		img: "",
		link: "",
		github: "",
		technologies: ["python"],
		license: "",
	},
	{
		featured: false,
		type: "public",
		title: "dagster-mlflow",
		summary: "Trial for dagster - mlflow",
		date: "2021-03-09",
		img: "/images/projects/dagster.webp",
		link: "",
		github: "",
		technologies: ["python", "dagster"],
		license: "MIT License",
	},
	{
		featured: false,
		type: "public",
		title: "awesome-panel",
		summary:
			"A repository for sharing knowledge on Panel by HoloViz in order to build awesome analytics apps in python",
		date: "2021-01-19",
		img: "",
		link: "",
		github: "https://github.com/awesome-panel/awesome-panel",
		technologies: ["jupyter"],
		license: "Apache License 2.0",
	},
	{
		featured: false,
		type: "private",
		title: "jetson-containers",
		summary: "Small docker for Jetson Xavier",
		date: "2020-12-20",
		img: "",
		link: "",
		github: "",
		technologies: ["docker"],
		license: "MIT License",
	},
];
export const detailsData = [
	{
		position:
			"Ingénieur de recherche, spécialité Développeur de logiciel scientifique",
		company: "IRT AESE - Saint Exupéry",
		companyLink: "https://www.irt-saintexupery.com",
		time: "July 2024 - Present (1 year 4 months)",
		address: "Toulouse, Occitanie, France",
		work: "En étroite collaboration avec les ingénieurs de l'équipe MDO, ma mission concerne le développement d'une approche Model-Based System Engineering (MBSE) et d'un plugin GEMSEO de gestion des données pour les projets de recherche du centre de compétence MDO (projets ANR ou Européens). Analyser et améliorer l'approche MBSE-MDAO pour assurer la consistance entre les processus MDO et les exigences programme. Explorer l'intégration de GEMSEO à un framework de management de données reposant sur des techniques d'intégration sémantique. Identifier et adapter des méthodologies répondant à des problématiques industrielles. Développer des éléments logiciels robustes et assurer leur maintenance. Écrire des tests unitaires et fonctionnels. Participer à la documentation des fonctionnalités développées. Participer aux jalons techniques des projets et présenter les résultats devant les membres des consortiums.",
	},
	{
		position: "Chief Technical Officer",
		company: "Jokosun",
		companyLink: "https://www.jokosun.com",
		time: "September 2021 - Present (2 years 5 months)",
		address: "Toulouse, Occitanie, France",
		work: "Responsible for all activities related to the Jokosun solar technology roadmap and Research & Development programs. Provide industry level insight and vision on technology trends. Drive scientific direction of the business unit to seek out and evaluate new technology, conduct feasibility testing and proof of concept, oversee product development process. Manage, implement, and ensure usability of information and computer technologies. Analyze various technologies' benefits for the company and integrate systems to realize improvements. Focus on EasyEnergyEverywhere.",
	},
	{
		position: "Powerplant Computational Physics Methods and Tools",
		company: "Airbus",
		companyLink: "https://www.airbus.com",
		time: "October 2019 - Present (4 years 4 months)",
		address: "Toulouse, France",
		work: "Define high-level design choices related to overall system structure and behavior in systems such as legacy information extraction from documents. Provide insights on DevOps setup. Balance between IT architecture definition and development with technologies like Kubernetes, Docker, Python, and NodeJS. Embrace a full end-to-end vision on digital topics.",
	},
	{
		position: "Head of Numerical Method for Fluid Mechanics",
		company: "boostHEAT",
		companyLink: "https://www.boostheat-group.com/fr/",
		time: "March 2015 - October 2019 (4 years 8 months)",
		address: "Ramonville-Saint-Agne",
		work: "Developed efficient heating and hot water systems fueled by natural gas and renewable energy. Led detailed knowledge acquisition about thermodynamic cycles and fluid flow control. Implemented simulation tools including CFD, Modelica, Digital Lab, and continuous technological intelligence using Machine Learning. Focused on reproducible research and multidisciplinary design optimization.",
	},
	{
		position: "Thermal Engineer in R&D Fields",
		company: "EPSILON Ingénierie",
		companyLink: "https://www.epsyl-alcen.com/en",
		time: "February 2012 - February 2015 (3 years 1 month)",
		address: "Toulouse",
		work: "In charge of developing coupling solutions between CFD software and Thermal software with autonomy. Tested Open Source technologies like OpenFOAM, OpenModelica, SALOME, CANTERA. Supervised thermal simulations support for industrial engines design. Wrote technical reports and specifications. Developed multi-physics code coupling interface for thermal analysis of systems.",
	},
	{
		position:
			"PhD: Modelling of the coupling between combustion and fouling inside furnace pipes",
		company: "CERFACS",
		companyLink: "https://cerfacs.fr/",
		time: "October 2008 - February 2012 (3 years 5 months)",
		address: "Toulouse",
		work: "Researched fouling in crude oil processing, focusing on heat exchanger performance degradation due to deposits formation. Developed a solid background in heat transfer phenomena. Collaborated with TOTAL group. Enhanced CERFACS codes for efficient coupling in parallel architecture.",
	},
	{
		position:
			"Topology analysis and Optimization of Double Swirl Burner in a combustion Chamber",
		company: "Turbomeca | Safran Helicopter Engine",
		companyLink:
			"https://www.safran-group.com/companies/safran-helicopter-engines",
		time: "May 2008 - September 2008 (5 months)",
		address: "Toulouse",
		work: "Developed tools to predict Swirl Number of a Double Swirl Burner. Improved topology using RANS and LES codes.",
	},
	{
		position: "Realisation of a graphic interface",
		company: "CERFACS",
		companyLink: "https://cerfacs.fr/",
		time: "February 2007 - March 2007 (2 months)",
		address: "Toulouse",
		work: "Developed a graphic interface in Tcl/Tk for an Acoustic codes.",
	},
];
export const educationData = [
	{
		type: "PhD",
		time: "2008 - 2011",
		place: "University of Toulouse",
		info: "Energy transfers: Focused on studying energy transfers, specifically in the context of the research topic.",
	},
	{
		type: "Ingénieur",
		time: "2005 - 2008",
		place: "ENSEEIHT",
		info: "Hydraulique et mécanique des fluides (Energie): Specialized in hydraulic and fluid mechanics with a focus on energy-related applications.",
	},
	{
		type: "Master",
		time: "2008",
		place: "University of Toulouse",
		info: "Dynamique des Fluides, Energétique et Transferts (DET): Studied fluid dynamics, energetics, and transfers as part of the master's program.",
	},
	{
		type: "Exchange Erasmus",
		time: "2007",
		place: "TU Hamburg-Harburg",
		info: "Energie et Mécanique des Fluides: Participated in an exchange program at TU Hamburg-Harburg, focusing on energy and fluid mechanics.",
	},
];
export const domain =
	process.env.NODE_ENV === "production"
		? "https://thomas.pedot.cc"
		: process.env.NEXT_PUBLIC_VERCEL_URL;

export const revalidatePage = process.env.NODE_ENV === "production" ? 30 : 0;
